version: "2.1"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=aidan
      - POSTGRES_PASSWORD=aidan
      - POSTGRES_DB=solver
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidan"]
      interval: 10s
      timeout: 5s
      retries: 5
